# Generated by Django 5.0.6 on 2024-06-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_question_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructure',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
