# Generated by Django 5.0.6 on 2024-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_feesstructure_total_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='paid_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
